# Mini Project - Classification of Wind Turbine Alarms
To start I will first look at the alarm data, and 1 quarter worth of data

In [1]:
import pandas as pd
import numpy as np
import os

# path = 'C:\\Users\\kthomas\\Google Drive\\SMU\\DataMining\\MiniProject\\Data\\'
path = '~/Documents/thomaskh522@gmail.com/SMU/DataMining/MiniProject/Data/'
# path = 'D:/Pattern/'
alarms = pd.read_csv(path + "tblAlarm2017_v2.csv")
alarms_desc = pd.read_csv(path + "Siemens_Fault_Code_Descriptions.csv")
q1 = pd.read_csv(path + "SCADAcombined2017Q1.csv")

In [15]:
alarms_desc = pd.read_csv(path + "Siemens_Fault_Code_Descriptions.csv")

In [16]:
alarms_desc.head()

Code                  Description Fault Type
0     0             System faultless          W
1   901   No. of freq. filters > Max          1
2   902  No. of analog filters > Max          1
3   903   Freq. filter not installed          1
4   904  Analog filter not installed          1

In [17]:
alarms.head()

Source  StationId  Type   Code           TimeOn TimeOff
0  System    2309007     0  50950  1/1/17 12:10 AM     NaN
1  System    2309008     0  50950  1/1/17 12:10 AM     NaN
2  System    2309009     0  50950  1/1/17 12:10 AM     NaN
3  System    2309010     0  50950  1/1/17 12:10 AM     NaN
4  System    2309011     0  50950  1/1/17 12:10 AM     NaN

In [2]:
#Now I need to merge the alarms with the alarm descriptions
df_merged_alarms = pd.merge(alarms, alarms_desc, on = ["Code"], how='inner')

In [20]:
df_merged_alarms.head()

Source  StationId  Type  Code          TimeOn         TimeOff  \
0    Wtc    2308996     0  3130  1/1/17 1:36 AM             NaN   
1    Wtc    2308996     0  3130  1/1/17 1:36 AM  1/1/17 1:40 AM   
2    Wtc    2308963     0  3130  1/1/17 2:43 AM             NaN   
3    Wtc    2308965     0  3130  1/1/17 2:45 AM             NaN   
4    Wtc    2308963     0  3130  1/1/17 2:43 AM  1/1/17 2:47 AM   

         Description Fault Type  
0  Pitch lubrication          1  
1  Pitch lubrication          1  
2  Pitch lubrication          1  
3  Pitch lubrication          1  
4  Pitch lubrication          1

In [3]:
df_merged_alarms['Description'].value_counts()

Stopped, untwisting cables        40665
Pitch lubrication                 12287
Hyd. for crane/cover activated     7428
Availability - low wind            6453
INU WARN: EM STOP (F081)           5700
Converter tripped, Auto Start      5560
INU ERR: EM STOP (F081)            5087
FRT detected by grid module        4996
Pitch pump. time too long,stop     2761
Stop for powerdown                 2478
Manual stop                        2442
Emergency switch activated         2345
Converter tripped, general         2207
Turbine in local operation         2180
UPS Battery Low                    1592
Hyd oil level error                1562
Pitchhydraulics superheated        1529
FT1 Sonic wind sensor error        1498
Remote stop Wake                   1420
Local, ad-hoc / repair work        1154
Gridvolt.<lower limit1             1068
Gridvolt.<lower limit2             1052
Gridvolt.<lower limit3             1010
Low lower voltage exceeded          898
Gridvolt.<lower limit4              824


In [4]:
T014 = df_merged_alarms.loc[df_merged_alarms['StationId'] == 2308974]
T014['Description'].value_counts()

Stopped, untwisting cables        1329
Pitch lubrication                  142
Availability - low wind             80
Stop for powerdown                  74
Pitch pump. time too long,stop      66
FRT detected by grid module         66
UPS Battery Low                     64
Hyd. for crane/cover activated      60
Main Bear Temp. Warning             50
INU WARN: EM STOP (F081)            48
Converter tripped, Auto Start       43
INU ERR: EM STOP (F081)             38
Main bearing temp. too high         36
Manual stop                         30
Turbine in local operation          28
Emergency switch activated          24
Converter tripped, general          23
INU ERR: COMM MODULE (7510)         22
Low lower voltage exceeded          16
Gridvolt.<lower limit1              16
Gridvolt.<lower limit2              16
Local, ad-hoc / repair work         14
Gridvolt.<lower limit3              12
Gen. Inv. Communication error       11
Main breaker tripped                11
Pitch pawl A Feedb. Stop 

In [13]:
q1.describe().transpose()

count          mean           std           min  \
StationId                 1111023.0  4.404165e+01  2.511075e+01  1.000000e+00   
CommunicationId           1111023.0  2.309002e+06  2.511075e+01  2.308959e+06   
NeighbourId               1111023.0  4.403962e+01  2.492885e+01  2.000000e+00   
NeighbourIdTwo            1111023.0  4.468494e+01  2.469343e+01  1.000000e+00   
XPos                      1111023.0  5.349489e+02  3.398955e+02  3.000000e+01   
YPos                      1111023.0  7.647548e+02  4.244587e+02  1.500000e+02   
wtc_SecAnemo_mean         1110941.0  7.930037e+00  3.387293e+00  0.000000e+00   
wtc_YawPos_mean           1110940.0  1.850828e+02  9.391416e+01  0.000000e+00   
wtc_GenRpm_mean           1110941.0  1.148163e+03  3.451305e+02  6.000000e-01   
wtc_HubLubGr_mean               0.0           NaN           NaN           NaN   
wtc_IceDetec_mean               0.0           NaN           NaN           NaN   
wtc_IMidBa_mean                 0.0           NaN           NaN           NaN   
wtc_IMidCa_mean                 0.0           NaN           NaN           NaN   
wtc_IMidAa_mean                 0.0           NaN           NaN           NaN   
wtc_MainSRpm_mean         1110941.0  1.267237e+01  3.809696e+00  0.000000e+00   
wtc_PitchRef_mean               0.0           NaN           NaN           NaN   
wtc_PitchRef_BladeA_mean  1110941.0  2.675378e+00  1.300413e+01 -2.029672e+00   
wtc_PitchRef_BladeB_mean  1110941.0  2.675240e+00  1.300300e+01 -2.029672e+00   
wtc_PitchRef_BladeC_mean  1110941.0  2.675385e+00  1.300298e+01 -2.029672e+00   
wtc_PitcRefA_mean         1110941.0  2.672963e+00  1.304287e+01 -2.300000e+00   
wtc_PriAnemo_mean         1110940.0  1.200000e+00  2.502089e-11  1.200000e+00   
wtc_PWMBa_mean                  0.0           NaN           NaN           NaN   
wtc_PWMCa_mean                  0.0           NaN           NaN           NaN   
wtc_PWMAa_mean                  0.0           NaN           NaN           NaN   
wtc_HubAnIn5_mean               0.0           NaN           NaN           NaN   
wtc_HubAnIn6_mean               0.0           NaN           NaN           NaN   
wtc_HubAnIn7_mean               0.0           NaN           NaN           NaN   
wtc_NacHumid_mean               0.0           NaN           NaN           NaN   
wtc_TwrHumid_mean         1110941.0  4.216198e+01  1.504279e+01  8.196293e+00   
wtc_VisMeter_endvalue           0.0           NaN           NaN           NaN   
...                             ...           ...           ...           ...   
wtc_IMSRotTm_mean         1110940.0  4.162664e+01  3.908607e+00  1.100000e+01   
wtc_IO1IntTm_mean               0.0           NaN           NaN           NaN   
wtc_IO2IntTm_mean               0.0           NaN           NaN           NaN   
wtc_IO3IntTm_mean               0.0           NaN           NaN           NaN   
wtc_NacelTmp_mean         1110940.0  2.165960e+01  5.847918e+00 -1.000000e+00   
wtc_NMMBrdTm_mean               0.0           NaN           NaN           NaN   
wtc_PFMaTemp_mean               0.0           NaN           NaN           NaN   
wtc_PFMCapTm_mean               0.0           NaN           NaN           NaN   
wtc_PFS1CapT_mean               0.0           NaN           NaN           NaN   
wtc_PFS1Temp_mean               0.0           NaN           NaN           NaN   
wtc_TrafL1Tm_mean               0.0           NaN           NaN           NaN   
wtc_TrafL2Tm_mean               0.0           NaN           NaN           NaN   
wtc_TrafL3Tm_mean               0.0           NaN           NaN           NaN   
wtc_TraOilTF_mean               0.0           NaN           NaN           NaN   
wtc_TraRooTF_mean               0.0           NaN           NaN           NaN   
wtc_ConvWTmp_mean         1110941.0  3.152444e+01  3.557419e+00  1.895848e+00   
wtc_ConvWTm2_mean               0.0           NaN           NaN           NaN   
wtc_HydOilTm_mean         1110940.0  3.078649e+01  2.258591e+

In [10]:
len(q1.Name.unique())

87

In [4]:
# investigate the data
# we may want to chose a subselection of data as there are 435 unique "Name" rows
# variables that I like Name, XPos, YPos, wtc_SecAnemo_mean, wtc_MainBTmp_mean, wtc_GFilB3Tm_mean
sub = q1.head(200)
sub[sub["TimeStamp"] == "2017-01-01 00:10:00.000"]

# position = q1.groupby("Name")
# position.head()

TimeStamp  Name  StationId  CommunicationId  \
0       2017-01-01 00:00:00.000  A001          1          2308959   
1       2017-01-01 00:00:00.000  T001          3          2308961   
2       2017-01-01 00:00:00.000  T002          4          2308962   
3       2017-01-01 00:00:00.000  T004          6          2308964   
4       2017-01-01 00:00:00.000  T005          7          2308965   
5       2017-01-01 00:00:00.000  T007          9          2308967   
6       2017-01-01 00:00:00.000  T008         10          2308968   
7       2017-01-01 00:00:00.000  T009         11          2308969   
8       2017-01-01 00:00:00.000  T010         12          2308970   
9       2017-01-01 00:00:00.000  T011         13          2308971   
10      2017-01-01 00:00:00.000  T012         14          2308972   
11      2017-01-01 00:00:00.000  T013         15          2308973   
12      2017-01-01 00:00:00.000  T014         16          2308974   
13      2017-01-01 00:00:00.000  T015         17          2308975   
14      2017-01-01 00:00:00.000  T016         18          2308976   
15      2017-01-01 00:00:00.000  T017         19          2308977   
16      2017-01-01 00:00:00.000  T018         20          2308978   
17      2017-01-01 00:00:00.000  T019         21          2308979   
18      2017-01-01 00:00:00.000  T021         23          2308981   
19      2017-01-01 00:00:00.000  T022         24          2308982   
20      2017-01-01 00:00:00.000  T024         26          2308984   
21      2017-01-01 00:00:00.000  T032         27          2308985   
22      2017-01-01 00:00:00.000  T034         29          2308987   
23      2017-01-01 00:00:00.000  T035         30          2308988   
24      2017-01-01 00:00:00.000  T036         31          2308989   
25      2017-01-01 00:00:00.000  T037         32          2308990   
26      2017-01-01 00:00:00.000  T038         33          2308991   
27      2017-01-01 00:00:00.000  T039         34          2308992   
28      2017-01-01 00:00:00.000  T040         35          2308993   
29      2017-01-01 00:00:00.000  T041         36          2308994   
...                         ...   ...        ...              ...   
957743  2017-03-30 23:10:00.000  T061         48          2309006   
957744  2017-03-30 23:10:00.000  T078         65          2309023   
957745  2017-03-30 23:10:00.000  T081         68          2309026   
957746  2017-03-30 23:10:00.000  T098         85          2309043   
957747  2017-03-30 23:20:00.000  A002          2          2308960   
957748  2017-03-30 23:20:00.000  T003          5          2308963   
957749  2017-03-30 23:20:00.000  T006          8          2308966   
957750  2017-03-30 23:20:00.000  T020         22          2308980   
957751  2017-03-30 23:20:00.000  T023         25          2308983   
957752  2017-03-30 23:20:00.000  T033         28          2308986   
957753  2017-03-30 23:20:00.000  T052         42          2309000   
957754  2017-03-30 23:20:00.000  T055         46          2309003   
957755  2017-03-30 23:20:00.000  T061         48          2309006   
957756  2017-03-30 23:20:00.000  T078         65          2309023   
957757  2017-03-30 23:20:00.000  T081         68          2309026   
957758  2017-03-30 23:20:00.000  T098         85          2309043   
957759  2017-03-30 23:30:00.000  A002          2          2308960   
957760  2017-03-30 23:30:00.000  T003          5          2308963   
957761  2017-03-30 23:30:00.000  T006          8          2308966   
957762  2017-03-30 23:30:00.000  T020         22          2308980   
957763  2017-03-30 23:30:00.000  T023         25          2308983   
957764  2017-03-30 23:30:00.000  T033         28          2308986   
957765  2017-03-30 23:30:00.000  T052         42          2309000   
957766  2017-03-30 23:30:00.000  T055         46          2309003   
957767  2017-03-30 23:30:00.000  T061         48          2309006   
957768  2017-03-30 23:30:00.000  T078         65          2309023   
957769  2017-03-30 2

In [3]:
# Investigate alarm data
alarms.head(10)
# uniqueStation = alarms["StationId"].unique()

Source  StationId  Type   Code           TimeOn TimeOff
0  System    2309007     0  50950  1/1/17 12:10 AM     NaN
1  System    2309008     0  50950  1/1/17 12:10 AM     NaN
2  System    2309009     0  50950  1/1/17 12:10 AM     NaN
3  System    2309010     0  50950  1/1/17 12:10 AM     NaN
4  System    2309011     0  50950  1/1/17 12:10 AM     NaN
5  System    2309012     0  50950  1/1/17 12:10 AM     NaN
6  System    2309013     0  50950  1/1/17 12:10 AM     NaN
7  System    2309014     0  50950  1/1/17 12:10 AM     NaN
8  System    2309015     0  50950  1/1/17 12:10 AM     NaN
9  System    2309016     0  50950  1/1/17 12:10 AM     NaN

In [8]:
# Next I need to turn the TimeOn Column into a timestamp
I also change the name of StationId to Communcation ID to make mergine easier
I also changed the name of DateTimeOn to TimeStamp to make merge eatier... I could have done this in assignment
from datetime import datetime
df_merged_alarms["DateTimeOn"] = df_merged_alarms["TimeOn"].apply(lambda x: datetime.strptime(x, '%m/%d/%y %I:%M %p'))
alarms["DateTimeOn"] = alarms["TimeOn"].apply(lambda x: datetime.strptime(x, '%m/%d/%y %I:%M %p'))
alarms=alarms.rename(columns = {'StationId':'CommunicationId'})
df_merged_alarms=df_merged_alarms.rename(columns={'StationId' : 'CommunicationId'})
# alarms.head()
df_merged_alarms.head()

Source  CommunicationId  Type  Code          TimeOn         TimeOff  \
0    Wtc          2308996     0  3130  1/1/17 1:36 AM             NaN   
1    Wtc          2308996     0  3130  1/1/17 1:36 AM  1/1/17 1:40 AM   
2    Wtc          2308963     0  3130  1/1/17 2:43 AM             NaN   
3    Wtc          2308965     0  3130  1/1/17 2:45 AM             NaN   
4    Wtc          2308963     0  3130  1/1/17 2:43 AM  1/1/17 2:47 AM   

         Description Fault Type          DateTimeOn  
0  Pitch lubrication          1 2017-01-01 01:36:00  
1  Pitch lubrication          1 2017-01-01 01:36:00  
2  Pitch lubrication          1 2017-01-01 02:43:00  
3  Pitch lubrication          1 2017-01-01 02:45:00  
4  Pitch lubrication          1 2017-01-01 02:43:00

In [15]:
# I think there is a problem merging on timestamp... I need to check the types of each one
print(type(alarms["DateTimeOn"][0]))
print(type(q1["TimeStamp"][0]))
q1["TimeStamp"][1000:1100]

<class 'pandas._libs.tslib.Timestamp'>
<class 'str'>


1000    2017-01-01 02:10:00.000
1001    2017-01-01 02:10:00.000
1002    2017-01-01 02:10:00.000
1003    2017-01-01 02:10:00.000
1004    2017-01-01 02:10:00.000
1005    2017-01-01 02:10:00.000
1006    2017-01-01 02:10:00.000
1007    2017-01-01 02:10:00.000
1008    2017-01-01 02:10:00.000
1009    2017-01-01 02:10:00.000
1010    2017-01-01 02:10:00.000
1011    2017-01-01 02:10:00.000
1012    2017-01-01 02:10:00.000
1013    2017-01-01 02:10:00.000
1014    2017-01-01 02:10:00.000
1015    2017-01-01 02:10:00.000
1016    2017-01-01 02:10:00.000
1017    2017-01-01 02:10:00.000
1018    2017-01-01 02:10:00.000
1019    2017-01-01 02:10:00.000
1020    2017-01-01 02:10:00.000
1021    2017-01-01 02:10:00.000
1022    2017-01-01 02:10:00.000
1023    2017-01-01 02:10:00.000
1024    2017-01-01 02:10:00.000
1025    2017-01-01 02:10:00.000
1026    2017-01-01 02:10:00.000
1027    2017-01-01 02:10:00.000
1028    2017-01-01 02:10:00.000
1029    2017-01-01 02:10:00.000
                 ...           
1070    

In [9]:
# Next Make a new column that makes the TimeStamp in Q1 an actual timestamp
q1["DateTimeOn"] = q1["TimeStamp"].apply(lambda x: datetime.strptime(x, '%Y-%m-%d %H:%M:%S.%f'))
q1['DateTimeOn'].head()

0   2017-01-01
1   2017-01-01
2   2017-01-01
3   2017-01-01
4   2017-01-01
Name: DateTimeOn, dtype: datetime64[ns]

In [20]:
#They look different... but are they really different?
print(q1['DateTimeOn'].head())
print(alarms['DateTimeOn'].head())

0   2017-01-01
1   2017-01-01
2   2017-01-01
3   2017-01-01
4   2017-01-01
Name: DateTimeOn, dtype: datetime64[ns]
0   2017-01-01 00:10:00
1   2017-01-01 00:10:00
2   2017-01-01 00:10:00
3   2017-01-01 00:10:00
4   2017-01-01 00:10:00
Name: DateTimeOn, dtype: datetime64[ns]


In [31]:
#Prove to myself that the values can be merged
print(type(q1["DateTimeOn"][0]))
print(type(alarms["DateTimeOn"][0]))
print(q1["DateTimeOn"][100])
print(alarms["DateTimeOn"][0])
q1["DateTimeOn"][100] == alarms["DateTimeOn"][0]

<class 'pandas._libs.tslib.Timestamp'>
<class 'pandas._libs.tslib.Timestamp'>
2017-01-01 00:10:00
2017-01-01 00:10:00


True

In [12]:
#Now I need to merge the alarms with the Q1 dataset
df_merged = pd.merge(q1, df_merged_alarms, on = ["DateTimeOn", "CommunicationId"], how='inner')

In [13]:
df_merged.head()

TimeStamp  Name  StationId  CommunicationId  NeighbourId  \
0  2017-01-01 05:00:00.000  T015         17          2308975            8   
1  2017-01-01 05:00:00.000  T015         17          2308975            8   
2  2017-01-01 05:00:00.000  T050         41          2308999           40   
3  2017-01-01 05:00:00.000  T050         41          2308999           40   
4  2017-01-01 05:10:00.000  T036         31          2308989           32   

   NeighbourIdTwo  XPos  YPos     wtc_CurTime_endvalue  wtc_SecAnemo_mean  \
0              16    30   900  2017-01-01 04:59:58.000           1.905287   
1              16    30   900  2017-01-01 04:59:58.000           1.905287   
2              44   950   750  2017-01-01 04:59:58.000           1.679922   
3              44   950   750  2017-01-01 04:59:58.000           1.679922   
4              33   145   750  2017-01-01 05:09:58.000           1.860418   

      ...      wtc_TrafoTMa_mean  wtc_BoostAva_mean          DateTimeOn  \
0     ...                  200.0                0.0 2017-01-01 05:00:00   
1     ...                  200.0                0.0 2017-01-01 05:00:00   
2     ...                  200.0                0.0 2017-01-01 05:00:00   
3     ...                  200.0                0.0 2017-01-01 05:00:00   
4     ...                  200.0                0.0 2017-01-01 05:10:00   

   Source  Type   Code          TimeOn         TimeOff  \
0     Wtc     0  10105  1/1/17 5:00 AM             NaN   
1     Wtc     0  10105  1/1/17 5:00 AM  1/1/17 5:12 AM   
2     Wtc     0  10105  1/1/17 5:00 AM             NaN   
3     Wtc     0  10105  1/1/17 5:00 AM  1/1/17 5:12 AM   
4     Wtc     0  10105  1/1/17 5:10 AM             NaN   

                  Description  Fault Type  
0  Stopped, untwisting cables           1  
1  Stopped, untwisting cables           1  
2  Stopped, untwisting cables           1  
3  Stopped, untwisting cables           1  
4  Stopped, untwisting cables           1  

[5 rows x 125 columns]

In [14]:
df_merged.shape

(2390, 125)

# Making class variables
First thought was to use OneHotEncoder. However, I wanted to first attempt a simpler approach. I identified the top 10 alarms and then sub-selected the dataset to only include those alarms. Since there were 10 variables I will attempt to use a SVM to classify the alarms.

In [46]:
top = df_merged_alarms['Description'].value_counts()

In [47]:
top = [x for x in dict(top[0:10]).keys()]
top

['Stopped, untwisting cables',
 'Pitch lubrication',
 'Hyd. for crane/cover activated',
 'Availability - low wind',
 'INU WARN: EM STOP (F081)',
 'Converter tripped, Auto Start',
 'INU ERR: EM STOP (F081)',
 'FRT detected by grid module',
 'Pitch pump. time too long,stop',
 'Stop for powerdown']

In [73]:
df_class = df_merged[df_merged["Description"].isin(top)]
df_class

<bound method NDFrame.describe of                     TimeStamp  Name  StationId  CommunicationId  NeighbourId  \
0     2017-01-01 05:00:00.000  T015         17          2308975            8   
1     2017-01-01 05:00:00.000  T015         17          2308975            8   
2     2017-01-01 05:00:00.000  T050         41          2308999           40   
3     2017-01-01 05:00:00.000  T050         41          2308999           40   
4     2017-01-01 05:10:00.000  T036         31          2308989           32   
5     2017-01-01 05:10:00.000  T036         31          2308989           32   
6     2017-01-01 05:10:00.000  T037         32          2308990           31   
7     2017-01-01 05:10:00.000  T037         32          2308990           31   
8     2017-01-01 05:10:00.000  T086         73          2309031           72   
9     2017-01-01 05:10:00.000  T086         73          2309031           72   
10    2017-01-01 05:20:00.000  T007          9          2308967            8   
11    

# Start SVM

In [89]:
from sklearn import svm
from sklearn.preprocessing import Imputer
# missing_values is the value of your placeholder, strategy is if you'd like mean, median or mode, and axis=0 means it calculates the imputation based on the other feature values for that sample
# borrowed from https://stackoverflow.com/questions/11441751/how-to-get-svms-to-play-nicely-with-missing-data-in-scikit-learn

#Set up data
y = df_class["Code"]
ref = df_class[["Code", "Description"]].groupby("Code")
ref.describe()

#get rid of all the string variables
X = df_class.drop(["Code", "Description", "TimeStamp", "wtc_CurTime_endvalue", "DateTimeOn", 
                   "TimeOn", "TimeOff", "Source", "Name", "Fault Type"], axis=1)

#Impute NaN Data so that sklearn will play nice
imp = Imputer(missing_values='NaN', strategy='mean', axis=0)
imp.fit(X)
train_X = imp.transform(X)


# Make test and training data
# http://scikit-learn.org/stable/modules/generated/sklearn.model_selection.train_test_split.html
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(train_X, y, test_size=0.33, random_state=42)

In [92]:
from sklearn.metrics import accuracy_score, confusion_matrix
svm_class = svm.SVC(C=0.5, kernel='rbf', degree=3, gamma='auto')
svm_class.fit(X_train,y_train)

#borrowed from Machine Learning notebook 4
y_hat = svm_class.predict(X_test)
acc = accuracy_score(y_test,y_hat)
conf = confusion_matrix(y_test,y_hat)
print('accuracy:', acc )
print(conf)

accuracy: 0.5810055865921788
[[  7  15   0   0   0   0   1   0   1   0]
 [  0  97   0   0   0   0   0   0   0   0]
 [  0  57   2   0   0   0   0   0   0   0]
 [  0   0   0  64   0   0   0   0   0   0]
 [  1  44   0   0   7   0   0   0   0   0]
 [  0  30   0   0   0 118   0   0   0   0]
 [  0   8   0   0   0   0   1   3  11   0]
 [  0   7   0   0   0   0   7   2  14   0]
 [  0   5   0   0   0   0   8  13   8   0]
 [  0   0   0   0   0   0   0   0   0   6]]
